version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - remate-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s       # Esperar más entre chequeos
      timeout: 5s
      retries: 10         # Más reintentos
      start_period: 30s   # Esperar más antes del primer chequeo

  servidor:
    build:
      context: .
      dockerfile: GrpcService/Dockerfile
    container_name: servidor-app
    ports:
      - "5000:5000"
    environment:
      TZ: America/Montevideo
      SERVER_IP: 0.0.0.0
      SERVER_PORT: 5000
      SERVER_IMAGE_PATH: /app/imagenes
      SERVER_DATA_PATH: /app/Servidor/Datos-Percargados
    volumes:
      - "C:/Users/Usuario/Desktop/imagenes_remates:/app/imagenes"
      - "C:/Users/Usuario/Desktop/datos_precargados:/app/Servidor/Datos-Percargados"
    networks:
      - remate-network
    depends_on:
      rabbitmq:
        condition: service_healthy

  estadisticas:
    build:
      context: .
      dockerfile: ServidorEstadisticasRest/Dockerfile
    container_name: servidor-estadisticas
    ports:
      - "5278:8080"
    networks:
      - remate-network
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  remate-network:
    driver: bridge
